cmake_minimum_required(VERSION 3.20)

project(vlinux)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# ASan and TSan.
if(ENABLE_ASAN AND ENABLE_TSAN)
    message(FATAL_ERROR "ASAN and TSAN cannot be enabled simultaneously")
endif()
if(ENABLE_ASAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        message(STATUS "ASAN enabled")
        add_compile_options(-fsanitize=address -g -O1 -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address)
    else()
        message(FATAL_ERROR "ASAN is only supported on Clang and GNU compilers")
    endif()
endif()
if(ENABLE_UBSAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        message(STATUS "UBSAN enabled")
        add_compile_options(-fsanitize=undefined -g -O1 -fno-omit-frame-pointer)
        add_link_options(-fsanitize=undefined)
    else()
        message(FATAL_ERROR "UBSAN is only supported on Clang and GNU compilers")
    endif()
endif()
if(ENABLE_TSAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        message(STATUS "TSAN enabled")
        add_compile_options(-fsanitize=thread -g -O1 -fno-omit-frame-pointer)
        add_link_options(-fsanitize=thread)
    else()
        message(FATAL_ERROR "TSAN is only supported on Clang and GNU compilers")
    endif()
endif()

find_package(PkgConfig REQUIRED)
pkg_check_modules(UNICORN REQUIRED IMPORTED_TARGET unicorn)
find_package(elfio CONFIG REQUIRED)
find_package(outcome CONFIG REQUIRED)
find_package(cpptrace CONFIG REQUIRED)

option(BUILD_TESTS "Build tests" ON)
if(BUILD_TESTS)
add_subdirectory(tests)
endif()

set(SRC_FILES src/mm.cpp src/vm.cpp src/task.cpp)
add_library(vlinux SHARED ${SRC_FILES})
target_compile_definitions(vlinux PRIVATE
    CMAKE_BUILD_DIR_PATH="${CMAKE_BINARY_DIR}"
)
target_include_directories(vlinux PUBLIC ${CMAKE_SOURCE_DIR}/include)
target_link_libraries(vlinux PUBLIC PkgConfig::UNICORN)
target_link_libraries(vlinux PUBLIC elfio::elfio)
target_link_libraries(vlinux PUBLIC outcome::hl)
